"""Update migration.

Revision ID: 2c8e1afbf92d
Revises: d5c58e769715
Create Date: 2023-03-04 18:53:24.588906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8e1afbf92d'
down_revision = 'd5c58e769715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
