"""Update remove colum migration.

Revision ID: 380904d2edac
Revises: 3fba541bcdda
Create Date: 2023-03-12 22:46:46.103522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380904d2edac'
down_revision = '3fba541bcdda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
