"""Update migration.

Revision ID: 6052b5138ecd
Revises: 7649f27bdc81
Create Date: 2023-02-26 16:31:43.828853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6052b5138ecd'
down_revision = '7649f27bdc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
