"""Update migration.

Revision ID: 7649f27bdc81
Revises: ef9507da7d13
Create Date: 2023-02-26 16:23:39.719600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7649f27bdc81'
down_revision = 'ef9507da7d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'num_upcoming_shows')
    # ### end Alembic commands ###
